# Generated by Django 2.2.28 on 2025-01-07 11:35

import datetime
from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecords',
            name='dob',
            field=models.DateField(default=datetime.date(2025, 1, 7)),
        ),
    ]
