# Generated by Django 2.2.28 on 2025-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20250107_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecords',
            name='dob',
            field=models.DateField(),
        ),
    ]
