# Generated by Django 2.2.28 on 2025-01-07 11:49

from django.db import migrations
from datetime import datetime
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True, default=datetime.now),
            preserve_default=False,
        ),
    ]
