# Generated by Django 2.2.28 on 2025-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Cancelled')], default=1),
        ),
    ]
