# Generated by Django 2.2.28 on 2025-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20250107_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='execution_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
