# Generated by Django 2.2.28 on 2025-01-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20250108_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_busy', models.BooleanField(default=False)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CustomerType')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.JobType')),
            ],
        ),
    ]
