# Generated by Django 2.2.28 on 2025-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'IN_PROGRESS'), (3, 'Completed'), (4, 'Cancelled')], default=1),
        ),
    ]
