# Generated by Django 2.2.28 on 2025-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20250108_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='execution_time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
